font:
  size: 8
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
  italic:
    family: Hack
    white: '0xebdbb2'

# Colors (Arc Dark)
colors:
  # Default colors
  primary:
    # background: '0x383c4a'
    background: '0x000000'
    foreground: '0xd3dae3'

  # Normal colors
  normal:
    black:   '0xabb3b1'
    red:     '0xe14245'
    green:   '0x5ca75b'
    yellow:  '0xf6ab32'
    blue:    '0x00ffd0'
    magenta: '0xa660c3'
    cyan:    '0x5294e2'
    white:   '0xa9a9aa'

  # Bright colors
  bright:
    black:   '0x616981'
    red:     '0xe16f7e'
    green:   '0xadd488'
    yellow:  '0xfdc35f'
    blue:    '0x8ca9bf'
    magenta: '0xe2afec'
    cyan:    '0x73c5e2'
    white:   '0xfcfcfc'
